/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menubar_login;

/**
 *
 * @author alan
 */
public class AdminToko extends javax.swing.JFrame {

    /**
     * Creates new form AdminToko
     */
    public AdminToko() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        user_Menu = new javax.swing.JMenu();
        logout_menuItem = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Kategori_menuItem = new javax.swing.JMenuItem();
        EntryBarang_menuItem = new javax.swing.JMenuItem();
        Laporan_menu = new javax.swing.JMenu();
        LaporanTransaksi_menuItem = new javax.swing.JMenuItem();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 718, Short.MAX_VALUE)
        );

        jMenuBar1.setMaximumSize(new java.awt.Dimension(565, 50000));
        jMenuBar1.setMinimumSize(new java.awt.Dimension(35, 150));

        user_Menu.setIcon(new javax.swing.ImageIcon("F:\\coding\\coding_java\\OOP\\sekolah\\modul_15\\tugas_praktikum\\Panel\\icon\\account_circle_FILL0_wght400_GRAD0_opsz48.png")); // NOI18N
        user_Menu.setText("User");
        user_Menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user_Menu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        user_Menu.setIconTextGap(15);
        user_Menu.setMargin(new java.awt.Insets(5, 0, 0, 0));
        user_Menu.setVerifyInputWhenFocusTarget(false);
        user_Menu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        logout_menuItem.setText("Log Out");
        logout_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_menuItemActionPerformed(evt);
            }
        });
        user_Menu.add(logout_menuItem);

        jMenuBar1.add(user_Menu);

        jMenu2.setIcon(new javax.swing.ImageIcon("F:\\coding\\coding_java\\OOP\\sekolah\\modul_15\\tugas_praktikum\\Panel\\icon\\inventory_FILL0_wght400_GRAD0_opsz48.png")); // NOI18N
        jMenu2.setText("Mangement Barang");
        jMenu2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu2.setIconTextGap(15);
        jMenu2.setMargin(new java.awt.Insets(5, 0, 0, 0));
        jMenu2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        Kategori_menuItem.setText("Kategori");
        Kategori_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Kategori_menuItemActionPerformed(evt);
            }
        });
        jMenu2.add(Kategori_menuItem);

        EntryBarang_menuItem.setText("Entry Barang");
        EntryBarang_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EntryBarang_menuItemActionPerformed(evt);
            }
        });
        jMenu2.add(EntryBarang_menuItem);

        jMenuBar1.add(jMenu2);

        Laporan_menu.setIcon(new javax.swing.ImageIcon("F:\\coding\\coding_java\\OOP\\sekolah\\modul_15\\tugas_praktikum\\Panel\\icon\\summarize_FILL0_wght400_GRAD0_opsz48.png")); // NOI18N
        Laporan_menu.setText("Laporan");
        Laporan_menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Laporan_menu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Laporan_menu.setIconTextGap(15);
        Laporan_menu.setMargin(new java.awt.Insets(5, 0, 0, 0));
        Laporan_menu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Laporan_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Laporan_menuActionPerformed(evt);
            }
        });

        LaporanTransaksi_menuItem.setText("Laporan Transaksi");
        LaporanTransaksi_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LaporanTransaksi_menuItemActionPerformed(evt);
            }
        });
        Laporan_menu.add(LaporanTransaksi_menuItem);

        jMenuBar1.add(Laporan_menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logout_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_menuItemActionPerformed
        // TODO add your handling code here
        
        dispose();
        new Menu_login().setVisible(true);
    }//GEN-LAST:event_logout_menuItemActionPerformed

    private void EntryBarang_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EntryBarang_menuItemActionPerformed
        // TODO add your handling code here:
        
        dispose();
        new Entry_Barang().setVisible(true);
    }//GEN-LAST:event_EntryBarang_menuItemActionPerformed

    private void Kategori_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Kategori_menuItemActionPerformed
        // TODO add your handling code here:
        
        dispose();
        new Form_Kategori().setVisible(true);
    }//GEN-LAST:event_Kategori_menuItemActionPerformed

    private void Laporan_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Laporan_menuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Laporan_menuActionPerformed

    private void LaporanTransaksi_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LaporanTransaksi_menuItemActionPerformed
        // TODO add your handling code here:
        
        dispose();
        new Laporan_Admin().setVisible(true);
    }//GEN-LAST:event_LaporanTransaksi_menuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminToko.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminToko().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem EntryBarang_menuItem;
    private javax.swing.JMenuItem Kategori_menuItem;
    private javax.swing.JMenuItem LaporanTransaksi_menuItem;
    private javax.swing.JMenu Laporan_menu;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JMenuItem logout_menuItem;
    private javax.swing.JMenu user_Menu;
    // End of variables declaration//GEN-END:variables
}
