/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Menubar_login;

import java.awt.event.*;
import java.awt.Window;
import java.awt.Frame;
import Menubar_login.Login_User;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JPanel;

/**
 *
 * @author adham PSN
 */
public class Menu_login extends javax.swing.JFrame {
    
    private boolean sudahLogin = false;
    private boolean sudahLogout = false;
    public static Menu_login Instance;
    public boolean masukLogin = false;
    public JPanel jPanel11;
    
    
    /**
     * Creates new form Menu_login
     */
    public Menu_login() {
        initComponents();
        
        Instance = this;
        
        jPanel11 = jPanel1;
        
        jikaLoginUser();
        
        keyPressed();
        Kosong();
    }
    
    
    private void sudahLogin() {
            
        // Pengkondisian untuk menangkap interaksi terhadap tombol login           
        if(sudahLogin == true ) {
                        
            logout_menuItem.setEnabled(true);
            
            transaksi_menu.setEnabled(true);
                
            sudahLogout();       
        } else {
                
            logout_menuItem.setEnabled(false);
            
            transaksi_menu.setEnabled(false);
        }     
    }
    
    
    private void sudahLogout() {
        
        // Pengkondisian untuk menangkap interaksi terhadap tombol logout
        if(sudahLogout == true ) {
                        
            login_menuItem.setEnabled(true);
                        
            logout_menuItem.setEnabled(false);
            
            transaksi_menu.setEnabled(false);
                        
        } else {
            
            login_menuItem.setEnabled(false);
        }
    }
    
    
    public void jikaLoginUser() {
        
        // Menunda proses login berjalan, sampai memasukkan username dan password di halaman Login_user   
        if(masukLogin == true) {
            
            sudahLogin = true;
            
            sudahLogin();
            
            sudahLogin = false;
        
        } else {
            
            sudahLogin();
        }
    }
    
    
    private void Kosong() {
    
        transaksi_menu.setEnabled(false);
    }
    
    
    private void keyPressed() {
    
        User_menu.setMnemonic(KeyEvent.VK_U);
        
        if(login_menuItem.isEnabled()) {
            
            login_menuItem.setMnemonic(KeyEvent.VK_L);
        } else if(logout_menuItem.isEnabled()) {
        
            logout_menuItem.setMnemonic(KeyEvent.VK_L);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        User_menu = new javax.swing.JMenu();
        login_menuItem = new javax.swing.JMenuItem();
        logout_menuItem = new javax.swing.JMenuItem();
        transaksi_menu = new javax.swing.JMenu();
        Form_Transaksi_menuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 628, Short.MAX_VALUE)
        );

        User_menu.setIcon(new javax.swing.ImageIcon("F:\\coding\\coding_java\\OOP\\sekolah\\modul_15\\tugas_praktikum\\HalamanLogin\\icon\\account_circle_FILL0_wght400_GRAD0_opsz48-sudah-diedit.png")); // NOI18N
        User_menu.setText("User");
        User_menu.setToolTipText("");
        User_menu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        User_menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        User_menu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        User_menu.setIconTextGap(20);
        User_menu.setMargin(new java.awt.Insets(10, 0, 5, 0));
        User_menu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        User_menu.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                User_menuMenuSelected(evt);
            }
        });

        login_menuItem.setText("Login");
        login_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_menuItemActionPerformed(evt);
            }
        });
        User_menu.add(login_menuItem);

        logout_menuItem.setText("Logout");
        logout_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_menuItemActionPerformed(evt);
            }
        });
        User_menu.add(logout_menuItem);

        jMenuBar1.add(User_menu);

        transaksi_menu.setIcon(new javax.swing.ImageIcon("F:\\coding\\coding_java\\OOP\\sekolah\\modul_15\\tugas_praktikum\\HalamanLogin\\icon\\shopping_cart_FILL0_wght400_GRAD0_opsz48-sudah-diedit.png")); // NOI18N
        transaksi_menu.setText("Transaksi");
        transaksi_menu.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        transaksi_menu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transaksi_menu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        transaksi_menu.setIconTextGap(20);
        transaksi_menu.setMargin(new java.awt.Insets(10, 0, 0, 5));
        transaksi_menu.setName(""); // NOI18N
        transaksi_menu.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        transaksi_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transaksi_menuActionPerformed(evt);
            }
        });

        Form_Transaksi_menuItem.setText("Form Transaksi");
        Form_Transaksi_menuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Form_Transaksi_menuItemActionPerformed(evt);
            }
        });
        transaksi_menu.add(Form_Transaksi_menuItem);

        jMenuBar1.add(transaksi_menu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(660, 851));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//GEN-FIRST:event_user_menuMenuSelected
    private void User_menuMenuSelected(javax.swing.event.MenuEvent evt) {
        // TODO add your handling code here:
    }
//GEN-LAST:event_user_menuMenuSelected
    
    
    private void login_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_menuItemActionPerformed
        // TODO add your handling code here:
                
        new Menu_UserAdmin().setVisible(true);
        
        dispose();
    }//GEN-LAST:event_login_menuItemActionPerformed

    
    private void logout_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_menuItemActionPerformed
        // TODO add your handling code here:
        
        sudahLogout = true;
        
        sudahLogout();
        
        sudahLogout = false;
        
    }//GEN-LAST:event_logout_menuItemActionPerformed

    private void transaksi_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transaksi_menuActionPerformed
        // TODO add your handling code here:
        
        dispose();
        new Form_Transaksi().setVisible(true);
    }//GEN-LAST:event_transaksi_menuActionPerformed

    private void Form_Transaksi_menuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Form_Transaksi_menuItemActionPerformed
        // TODO add your handling code here:
        
        dispose();
        new Form_Transaksi().setVisible(true);
    }//GEN-LAST:event_Form_Transaksi_menuItemActionPerformed
 


    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Form_Transaksi_menuItem;
    private javax.swing.JMenu User_menu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem login_menuItem;
    private javax.swing.JMenuItem logout_menuItem;
    private javax.swing.JMenu transaksi_menu;
    // End of variables declaration//GEN-END:variables
}
